Test failures using IBM Java 5
1. ReflectionBasedReferenceTypeDelegateTest.testCompareSubclassDelegates() junit.framework.AssertionFailedError: Errors:Couldn't find void java.util.HashMap.onEntry() in the bcel set Couldn't find void java.util.HashMap.onExit() in the bcel set Couldn't find void java.util.HashMap.transfer0(java.util.HashMap$Entry[]) in the bcel set ? ? ? ? at junit.framework.Assert.fail(Assert.java:47) ? ? ? ? at junit.framework.Assert.assertTrue(Assert.java:20) ? ? ? ? at org.aspectj.weaver.reflect.ReflectionBasedReferenceTypeDelegateTest.testCompareSubclassDelegates(ReflectionBasedReferenceTypeDelegateTest.java:278) ? ? ? ? at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ? ? ? ? at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64) ? ? ? ? at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ? ? ? ? at java.lang.reflect.Method.invoke(Method.java:615) ? ? ? ? at junit.framework.TestCase.runTest(TestCase.java:154) ? ? ? ? at junit.framework.TestCase.runBare(TestCase.java:127) ? ? ? ? at junit.framework.TestResult$1.protect(TestResult.java:106) ? ? ? ? at junit.framework.TestResult.runProtected(TestResult.java:124) ? ? ? ? at junit.framework.TestResult.run(TestResult.java:109) ? ? ? ? at junit.framework.TestCase.run(TestCase.java:118) ? ? ? ? at junit.framework.TestSuite.runTest(TestSuite.java:208) ? ? ? ? at junit.framework.TestSuite.run(TestSuite.java:203) ? ? ? ? at junit.framework.TestSuite.runTest(TestSuite.java:208) ? ? ? ? at junit.framework.TestSuite.run(TestSuite.java:203) ? ? ? ? at junit.framework.TestSuite.runTest(TestSuite.java:208) ? ? ? ? at junit.framework.TestSuite.run(TestSuite.java:203) ? ? ? ? at junit.framework.TestSuite.runTest(TestSuite.java:208) ? ? ? ? at junit.framework.TestSuite.run(TestSuite.java:203) ? ? ? ? at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:478) ? ? ? ? at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:344) ? ? ? ? at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:196) This failure occures because when we compare BeclWorld with ReflectionWorld we are still picking up the default (Sun) version of HashMap in JRE15_LIB for BCEL. The solution is to create both worlds with the same class loader. 2. Ajc150Tests.testModifierOverrides() junit.framework.AssertionFailedError: Expecting output: execution(void pr119749.C.m()): execMe[@pr119749$Me()] execution(void pr119749.C.m()): execEx But found output: execution(void pr119749.C.m()): execMe[@pr119749.Me()] execution(void pr119749.C.m()): execEx First difference is on line 1 ? ? ? ? at junit.framework.Assert.fail(Assert.java:47) ? ? ? ? at org.aspectj.testing.OutputSpec.matchAgainst(OutputSpec.java:58) ? ? ? ? at org.aspectj.testing.RunSpec.execute(RunSpec.java:61) ? ? ? ? at org.aspectj.testing.AjcTest.runTest(AjcTest.java:68) ? ? ? ? at org.aspectj.testing.XMLBasedAjcTestCase.runTest(XMLBasedAjcTestCase.java:111) ? ? ? ? at org.aspectj.systemtest.ajc150.Ajc150Tests.testModifierOverrides(Ajc150Tests.java:852) ? ? ? ? at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ? ? ? ? at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64) ? ? ? ? at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ? ? ? ? at java.lang.reflect.Method.invoke(Method.java:615) ? ? ? ? at junit.framework.TestCase.runTest(TestCase.java:154) ? ? ? ? at junit.framework.TestCase.runBare(TestCase.java:127) ? ? ? ? at junit.framework.TestResult$1.protect(TestResult.java:106) ? ? ? ? at junit.framework.TestResult.runProtected(TestResult.java:124) ? ? ? ? at junit.framework.TestResult.run(TestResult.java:109) ? ? ? ? at junit.framework.TestCase.run(TestCase.java:118) ? ? ? ? at junit.framework.TestSuite.runTest(TestSuite.java:208) ? ? ? ? at junit.framework.TestSuite.run(TestSuite.java:203) ? ? ? ? at junit.framework.TestSuite.runTest(TestSuite.java:208) ? ? ? ? at junit.framework.TestSuite.run(TestSuite.java:203) ? ? ? ? at junit.extensions.TestDecorator.basicRun(TestDecorator.java:22) ? ? ? ? at junit.extensions.TestSetup$1.protect(TestSetup.java:19) ? ? ? ? at junit.framework.TestResult.runProtected(TestResult.java:124) ? ? ? ? at junit.extensions.TestSetup.run(TestSetup.java:23) ? ? ? ? at junit.framework.TestSuite.runTest(TestSuite.java:208) ? ? ? ? at junit.framework.TestSuite.run(TestSuite.java:203) ? ? ? ? at junit.framework.TestSuite.runTest(TestSuite.java:208) ? ? ? ? at junit.framework.TestSuite.run(TestSuite.java:203) ? ? ? ? at junit.framework.TestSuite.runTest(TestSuite.java:208) ? ? ? ? at junit.framework.TestSuite.run(TestSuite.java:203) ? ? ? ? at junit.framework.TestSuite.runTest(TestSuite.java:208) ? ? ? ? at junit.framework.TestSuite.run(TestSuite.java:203) ? ? ? ? at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:478) ? ? ? ? at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:344) ? ? ? ? at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:196) This failure is due a difference between JDKs in the implementation of toString() for annotations.